# Generated by Django 4.2.3 on 2023-07-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('programa_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Programa', models.CharField(max_length=1000)),
                ('area_Tematica', models.CharField(choices=[('CYT', 'Ciencia y tecnología'), ('CUL', 'Cultura'), ('ECO', 'Economía'), ('EDU', 'Educación'), ('MAM', 'Medio ambiente'), ('MOV', 'Movilidad'), ('SAL', 'Salud'), ('SEG', 'Seguridad pública'), ('TUR', 'Turismo'), ('VIV', 'Vivienda'), ('OTR', 'Otro')], max_length=3)),
                ('nombre_Institucion', models.CharField(max_length=1000)),
                ('descripcion_Fondo', models.CharField(max_length=1000)),
                ('origen', models.CharField(choices=[('INT', 'Internacional'), ('GUB', 'Gubernamental'), ('PRI', 'Privado'), ('OTR', 'Otro')], max_length=3)),
                ('grupo_De_Atencion', models.CharField(choices=[('AYD', 'Artistas y diseñadores'), ('EST', 'Estudiantes'), ('PED', 'Personal docente'), ('INV', 'Investigadores, inventores y científicos'), ('PG', 'Población general'), ('PYC', 'Productores y campesinos'), ('PM', 'Personas mayores'), ('MUJ', 'Mujeres'), ('JOV', 'Jóvenes'), ('PCD', 'Personas con discapacidad'), ('POB', 'Personas en situación de pobreza'), ('IND', 'Indígenas'), ('DEP', 'Deportistas'), ('OTR', 'Otro')], max_length=3)),
                ('tipo_De_Poblacion', models.CharField(choices=[('AUT', 'Autoridades'), ('EMP', 'Empresas o emprendedores'), ('ONG', 'Organizaciones no gubernamentales'), ('PF', 'Personas físicas'), ('PM', 'Personas morales'), ('ND', 'No disponible'), ('OTR', 'Otro')], max_length=3)),
                ('requerimientos', models.CharField(max_length=1000)),
                ('tipo_Apoyo', models.CharField(choices=[('AT', 'Asistencia técnica'), ('CP', 'Capacitación'), ('CR', 'Crédito'), ('EC', 'Económico'), ('EN', 'En especie'), ('ND', 'No disponible'), ('OTR', 'Otro')], max_length=3)),
                ('descripcion_Apoyo', models.CharField(max_length=1000)),
                ('importe', models.IntegerField(null=True)),
                ('maximo', models.BooleanField(null=True)),
                ('moneda', models.CharField(max_length=3)),
                ('periodicidad', models.CharField(choices=[('DI', 'Diaria'), ('SE', 'Semanal'), ('QU', 'Quincenal'), ('ME', 'Mensual'), ('BI', 'Bimestral'), ('TR', 'Trimestral'), ('SM', 'Semestral'), ('AN', 'Anual'), ('PU', 'Pago único'), ('OTR', 'Otro')], max_length=3)),
                ('convocatoria_Inicio', models.DateField(null=True)),
                ('convocatoria_Cierre', models.DateField(null=True)),
                ('activo', models.BooleanField(null=True)),
                ('contacto', models.CharField(default='Contacto', max_length=1000, null=True)),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
