# Generated by Django 4.2.3 on 2023-07-13 04:31

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaFuentesFinanciamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='convocatoria_Cierre',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='convocatoria_Inicio',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
    ]
