# Generated by Django 4.2.3 on 2023-07-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaFuentesFinanciamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuentes',
            old_name='area_tematica',
            new_name='area_Tematica',
        ),
        migrations.RenameField(
            model_name='fuentes',
            old_name='grupo_atn',
            new_name='grupo_De_Atencion',
        ),
        migrations.RenameField(
            model_name='fuentes',
            old_name='tipo_pob',
            new_name='tipo_De_Poblacion',
        ),
    ]
