# Generated by Django 4.2.3 on 2023-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaFuentesFinanciamiento', '0002_rename_area_tematica_fuentes_area_tematica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuentes',
            name='contacto',
            field=models.CharField(default='Contacto', max_length=1000),
        ),
    ]
