# Generated by Django 4.2.3 on 2023-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaFuentesFinanciamiento', '0003_fuentes_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentes',
            name='activo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='contacto',
            field=models.CharField(default='Contacto', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='convocatoria_Cierre',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='convocatoria_Inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='importe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='maximo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='telefono',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
